version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbnode
    volumes:
      - ./mysql/dbdata:/var/lib/mysql 
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - node_mysql
  node:
    build: ./node
    container_name: node
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - mysql
    networks:
      - node_mysql
      - node_nginx
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 10s
    command: node index.js
    # tty: true
  
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - node_nginx
    depends_on:
      - node
    entrypoint: dockerize -wait tcp://node:3000 -timeout 20s nginx -g "daemon off;"
    

networks:
  node_mysql:
    driver: bridge
  node_nginx:
    driver: bridge
